.gitignore
src/main/java/aqa.java.core/lesson1.lshcherbak/HelloWorld.java
src/main/java/aqa.java.core/lesson1/LauraShcherbak/HelloWorld.java

@andrii-kylo Please review and merge

[Lesson 1] HW 1 added

---

src/main/java/aqa/core/lesson1/halynakuchabska/Homework1Kuchabska.java
src/main/java/aqa/core/lesson2/MykhailoOsadtsiv/HomeWork2.java
src/main/java/aqa/core/lesson2/MykhailoOsadtsiv/SlotoKingBone.java
src/main/java/aqa/core/lesson3/MykhailoOsadtsiv/HomeWork3.java

Mykhailo osadtsiv

---

src/main/java/aqa/core/lesson2/NataSkrypak/homeWork2Skrypak/hw2Skrypak.java
src/main/java/aqa/core/lesson2/NataliaSkrypak/HW2

Natalia skrypak

---

src/main/java/aqa/core/lesson2/RomanovYevgen/DataTypes.java
src/main/java/aqa/core/lesson2/RomanovYevgen/HomeWork2.java
src/main/java/aqa/core/lesson2/RomanovYevgen/SimpleInput.java

corrected figured out, worked on bugs

Romanov yevgen corrected figured out

---

src/main/java/aqa/core/lesson1/HalynaKuchabska/Homework1Kuchabska.java
src/main/java/aqa/core/lesson2/DianaHrymaliuk/HomeWork2.java
src/main/java/aqa/core/lesson2/dhrymaliuk/HomeWork2.java

Diana Hrymaliuk

---

src/main/java/aqa/core/lesson1/halynakuchabska/Homework1Kuchabska.java
src/main/java/aqa/core/lesson2/vriaboshapka/Homework2.java

Vriaboshapka

---

src/main/java/aqa/core/lesson2/mbednarchuk/HomeWork2.java

HW 2|Data types and simple arithmetic operations

Markiyan bednarchuk

---

src/main/java/aqa/core/lesson2/liubovpylypenko/DataTypes.java
src/main/java/aqa/core/lesson2/liubovpylypenko/SimpleInput.java

Homework lesson 2

---

src/main/java/aqa/core/lesson2/kuchabska/Homework2Kuchabska.java

Homework 2 Kuchabska Halyna added

---

src/main/java/aqa/core/lesson3/kuchabska/Homework3Kuchabska.java
src/main/java/aqa/core/lesson3/kuchabska/homework3_kuchabska.java

Lesson3 kuchabska

---

src/main/java/aqa/core/lesson1/halynakuchabska/Homework1Kuchabska.java
src/main/java/aqa/core/lesson3/NazarVdovych/HomeWork3.java

Vdovych lesson 3

---

src/main/java/aqa/core/lesson3/Romanov/Yevgen/Calculator.java
src/main/java/aqa/core/lesson3/Romanov/Yevgen/HomeWork3.java
src/main/java/aqa/core/lesson_4/Romanov/Yevgen/ArraysLess.java
src/main/java/aqa/core/lesson_4/Romanov/Yevgen/LinearSearch.java

Romanov_Yevgen_homework3_ok

---

src/main/java/aqa/core/lesson3/IrynaKrechetova/Lesson3part1.java
src/main/java/aqa/core/lesson3/IrynaKrechetova/Lesson3part2.java
src/main/java/aqa/core/lesson4/akylo/IrynaKrechetova/Lesson4.java

Lesson 3 and Lesson 4.

---

src/main/java/aqa/core/lesson1/halynakuchabska/Homework1Kuchabska.java
src/main/java/aqa/core/lesson2/LiudaKapusniak/Homework2.java

Please check my late homework2. Thank you.

Liuda kapusniak

---

src/main/java/aqa/core/lesson4/LiubovPylypenko/HomeTasks4.java

HomeTasks 4 is done by L.Pylypenko

HomeTasks 4 is done by L.Pylypenko

---

src/main/java/aqa/core/less4/YRomanov/ArrayLess.java
src/main/java/aqa/core/less4/YRomanov/LinearSearch.java

HomeWork4_YRomanov

---

src/main/java/aqa/core/lesson4/akylo/LauraShcherbak/HomeWork4.java

@andrii-kylo Could you please review and merge

[Lesson 4] HW 4 added

---

src/main/java/aqa/core/lesson3/KhrystynaFedechko/HomeWork3.java

Lesson3fedechko

---

src/main/java/aqa/core/lesson3/kuchabska/Homework3Kuchabska.java
src/main/java/aqa/core/lesson3/kuchabska/homework3_kuchabska.java
src/main/java/aqa/core/lesson4/kuchabska/Homework4Kuchabska.java

Lesson4 kuchabska

---

src/main/java/aqa/core/lesson3/HomeWork3.java
src/main/java/aqa/core/lesson3/MarkiyanBednarchuk/HomeWork3.java

Lesson3|Sorting arrays,console calculator

---

src/main/java/aqa/core/lesson4/akylo/MarkiyanBednarchuk/HW4.java

Lesson4|Linear and binary searching

---

src/main/java/aqa/core/lesson3/LuibovPylypenko/HomeTasks3.java

HomeTasks 3 is done by Liubov Pylypenko.

HomeTasks 3 is done by Liubov Pylypenko.

---

src/main/java/aqa/core/lesson5/LiubovPylypenko/HomeTasks5.java

HomeTasks 5 is done by L.Pylypenko

HomeTasks 5 is done by L.Pylypenko

---

src/main/java/aqa/core/lesson5/akylo/IrynaKrechetova/Homework5.java

homework 5 - Krechetova

---

src/main/java/aqa/core/lesson3/LiudaKapusniak/Homework3.java

Could you please check my Homework 3?
Thank you.

Homework3Kapusniak

---

src/main/java/aqa/core/lesson5/LauraShcherbak/MethodsTask.java

@andrii-kylo  Could you please review and merge?

[Lesson 5] HW 5 added

---

src/main/java/aqa/core/lesson5/akylo/MarkiyanBednarchuk/HomeWork5.java

Lesson5|Method Task|Sorting methods

---

src/main/java/aqa/core/lesson6/LauraShcherbak/HomeWork6.java
src/main/java/aqa/core/lesson6/LauraShcherbak/Sakura.java

[Lesson 6] small improvements added for HW 6

---

src/main/java/aqa/core/lesson7/LauraShcherbak/Circle.java
src/main/java/aqa/core/lesson7/LauraShcherbak/Main.java
src/main/java/aqa/core/lesson7/LauraShcherbak/Rectangle.java
src/main/java/aqa/core/lesson7/LauraShcherbak/Shape.java
src/main/java/aqa/core/lesson7/LauraShcherbak/Triangle.java

[Lesson 7] HW 7 added

---

src/main/java/aqa/core/lesson7/HalynaKuchabska/Circle.java
src/main/java/aqa/core/lesson7/HalynaKuchabska/Main.java
src/main/java/aqa/core/lesson7/HalynaKuchabska/Rectangle.java
src/main/java/aqa/core/lesson7/HalynaKuchabska/Shape.java
src/main/java/aqa/core/lesson7/HalynaKuchabska/Triangle.java

Lesson7 kuchabska

---

src/main/java/aqa/core/lesson7/LiubovPylypenko/Circle.java
src/main/java/aqa/core/lesson7/LiubovPylypenko/HomeTasks7.java
src/main/java/aqa/core/lesson7/LiubovPylypenko/Rectangle.java
src/main/java/aqa/core/lesson7/LiubovPylypenko/Shape.java
src/main/java/aqa/core/lesson7/LiubovPylypenko/Triangle.java

HomeTasks 7 is done by L.Pylypenko

HomeTasks 7 is done by L.Pylypenko

---

src/main/java/aqa/core/lesson7/les7Skrypak/Circle.java
src/main/java/aqa/core/lesson7/les7Skrypak/Main.java
src/main/java/aqa/core/lesson7/les7Skrypak/Rectangle.java
src/main/java/aqa/core/lesson7/les7Skrypak/Shape.java
src/main/java/aqa/core/lesson7/les7Skrypak/Triangle.java

mistakes about privat access to parent(

lesson 7. Skrypak

---

src/main/java/aqa/core/lesson3/barabash/Hw3.java
src/main/java/aqa/core/lesson4/barabash/Hw4.java

rostyslav barabash commit

---

src/main/java/aqa/core/lesson6/akylo/nsobol6/Helmet.java
src/main/java/aqa/core/lesson6/akylo/nsobol6/Homework6.java
src/main/java/aqa/core/lesson6/akylo/nsobol6/Homework61.java

Lesson 6 - Homework.

---

src/main/java/aqa/core/lesson7/nsobol7/Calculate.java
src/main/java/aqa/core/lesson7/nsobol7/Circle.java
src/main/java/aqa/core/lesson7/nsobol7/Rectangle.java
src/main/java/aqa/core/lesson7/nsobol7/Shape.java
src/main/java/aqa/core/lesson7/nsobol7/Triagle.java

Lesson 7 - Homework.

---

src/main/java/aqa/core/lesson7/Circle.java
src/main/java/aqa/core/lesson7/Rectangle.java
src/main/java/aqa/core/lesson7/Shape.java
src/main/java/aqa/core/lesson7/Triangle.java

HomeWork7 ShapeTriangleCircleRectangle

---

src/main/java/aqa/core/lesson8/lauraShcherbak/Circle.java
src/main/java/aqa/core/lesson8/lauraShcherbak/Drawable.java
src/main/java/aqa/core/lesson8/lauraShcherbak/Main.java
src/main/java/aqa/core/lesson8/lauraShcherbak/Rectangle.java
src/main/java/aqa/core/lesson8/lauraShcherbak/Shape.java
src/main/java/aqa/core/lesson8/lauraShcherbak/ShapeComparator.java
src/main/java/aqa/core/lesson8/lauraShcherbak/Triangle.java

[Lesson 8] HW 8 added

---

src/main/java/aqa/core/lesson8/lpylypenko/Circle.java
src/main/java/aqa/core/lesson8/lpylypenko/Drawable.java
src/main/java/aqa/core/lesson8/lpylypenko/HomeTasks8.java
src/main/java/aqa/core/lesson8/lpylypenko/Rectangle.java
src/main/java/aqa/core/lesson8/lpylypenko/Shape.java
src/main/java/aqa/core/lesson8/lpylypenko/SortByColor.java
src/main/java/aqa/core/lesson8/lpylypenko/Triangle.java

Liubov Pylypenko Home Task 8 - is done.

Liubov pylypenko8

---

src/main/java/aqa/core/lesson9/irynaKrechetova/Main.java

Krechetova l9

---

src/main/java/aqa/core/lesson8/halynakuchabska/Circle.java
src/main/java/aqa/core/lesson8/halynakuchabska/Drawable.java
src/main/java/aqa/core/lesson8/halynakuchabska/Main.java
src/main/java/aqa/core/lesson8/halynakuchabska/Rectangle.java
src/main/java/aqa/core/lesson8/halynakuchabska/Shape.java
src/main/java/aqa/core/lesson8/halynakuchabska/Triangle.java

homework8 Halyna Kuchabska

---

src/main/java/aqa/core/lesson9/halynakuchabska/Main.java

Homework 9 Kychabska

---

src/main/java/aqa/core/lesson9/Main.java
src/main/java/aqa/core/lesson9/Main2.java
src/main/java/aqa/core/lesson9/Main3.java

Lesson9|String

---

src/main/java/aqa/core/lesson1/halynakuchabska/Homework1Kuchabska.java
src/main/java/aqa/core/lesson9/VdovychNazar/Main.java
src/main/java/aqa/core/lesson9/VdovychNazar/Main2.java
src/main/java/aqa/core/lesson9/VdovychNazar/Main3.java

HomeWork9 add

---

src/main/java/aqa/core/lesson9/lauraShcherbak/Main.java

@andrii-kylo Could you please review and approve?

[Lesson 9] HW 9 added

---

src/main/java/aqa/core/lesson9/nSkrypak/Main.java
src/main/java/aqa/core/lesson9/nSkrypak/Main1.java

lesson 9/ first task

---

src/main/java/aqa/core/lesson9/lpylypenko/HomeTasks9.java

HomeTasks 9 is done by L.Pylypenko.

HomeTasks 9 is done by L.Pylypenko.

---

src/main/java/aqa/core/lesson10/akylo/MarkiyanBednarchuk/Main.java
src/main/java/aqa/core/lesson7/MarkiyanBednarchuk/Circle.java
src/main/java/aqa/core/lesson7/MarkiyanBednarchuk/Main.java
src/main/java/aqa/core/lesson7/MarkiyanBednarchuk/Rectangle.java
src/main/java/aqa/core/lesson7/MarkiyanBednarchuk/Shape.java
src/main/java/aqa/core/lesson7/MarkiyanBednarchuk/Triangle.java

Lesson7|Shapes

---

src/main/java/aqa/core/lesson10/KostiantynStavruk/Main.java
src/main/java/aqa/core/lesson10/KostiantynStavruk/MyException.java
src/main/java/aqa/core/lesson10/KostiantynStavruk/MyTest.java

Task_3 is in private messages (Slack), because in the task was written "create a new project", so I pushed it in my repository.

Kostiantyn Stavruk HW#10 (task1&task2)

---

src/main/java/aqa/core/lesson10/akylo/kuchabskahaluna/InvalidAgeException.java
src/main/java/aqa/core/lesson10/akylo/kuchabskahaluna/Main.java
src/main/java/aqa/core/lesson10/akylo/kuchabskahaluna/MyException.java
src/main/java/aqa/core/lesson10/akylo/kuchabskahaluna/MyTest.java
src/main/java/aqa/core/lesson10/akylo/kuchabskahaluna/Person.java

homework 10 kuchabska

---

src/main/java/aqa/core/lesson10/lauraShcherbak/ExceptionDemo/InvalidAgeException.java
src/main/java/aqa/core/lesson10/lauraShcherbak/ExceptionDemo/Main.java
src/main/java/aqa/core/lesson10/lauraShcherbak/ExceptionDemo/Person.java
src/main/java/aqa/core/lesson10/lauraShcherbak/Main.java
src/main/java/aqa/core/lesson10/lauraShcherbak/MyException.java
src/main/java/aqa/core/lesson10/lauraShcherbak/MyTest.java

[Lesson 10] HW 10 added

---

src/main/java/aqa/core/lesson10/lpylypenko/ExceptionDemo.java
src/main/java/aqa/core/lesson10/lpylypenko/HomeTasks10.java
src/main/java/aqa/core/lesson10/lpylypenko/InvalidAgeException.java
src/main/java/aqa/core/lesson10/lpylypenko/MyException.java
src/main/java/aqa/core/lesson10/lpylypenko/MyTest.java
src/main/java/aqa/core/lesson10/lpylypenko/Person.java

Home Task 10 is done by L. Pylypenko

Home Task 10 is done by L. Pylypenko

---

src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/Main.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/MyException.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/MyTest.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/Silmarillion.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/company/Company.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/company/Employee.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/company/HumanResourcesDepartment.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/company/Test.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/company/ToLowSalary.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/exceptionDemo/InvalidAgeException.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/exceptionDemo/Main.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/exceptionDemo/Person.java

M osadtsiv 10

---

src/main/java/aqa/core/lesson10/irynaKrechetova/exceptionDemo/InvalidAgeException.java
src/main/java/aqa/core/lesson10/irynaKrechetova/exceptionDemo/Main.java
src/main/java/aqa/core/lesson10/irynaKrechetova/exceptionDemo/Person.java
src/main/java/aqa/core/lesson10/irynaKrechetova/part1/Main.java
src/main/java/aqa/core/lesson10/irynaKrechetova/part1/myExeption.java
src/main/java/aqa/core/lesson10/irynaKrechetova/part1/myTest.java

Krechetova 10

---

src/main/java/aqa/core/lesson10/Nazarvdocyh_10/ExceptionDemo/InvalidAgeException.java
src/main/java/aqa/core/lesson10/Nazarvdocyh_10/ExceptionDemo/Main.java
src/main/java/aqa/core/lesson10/Nazarvdocyh_10/ExceptionDemo/Person.java
src/main/java/aqa/core/lesson10/Nazarvdocyh_10/Main.java
src/main/java/aqa/core/lesson10/Nazarvdocyh_10/MyClass.java
src/main/java/aqa/core/lesson10/Nazarvdocyh_10/MyException.java

Nazarvdovych 10

---

src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/Main.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/MyException.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/MyTest.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/Silmarillion.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/company/Company.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/company/Employee.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/company/HumanResourcesDepartment.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/company/Test.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/company/ToLowSalary.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/exceptionDemo/InvalidAgeException.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/exceptionDemo/Main.java
src/main/java/aqa/core/lesson10/mykhailo_osadtsiv/exceptionDemo/Person.java
src/main/java/aqa/core/lesson11/mykhailo_osadtsiv/company/ChooseYourDestiny.java
src/main/java/aqa/core/lesson11/mykhailo_osadtsiv/company/Company.java
src/main/java/aqa/core/lesson11/mykhailo_osadtsiv/company/Comparator.java
src/main/java/aqa/core/lesson11/mykhailo_osadtsiv/company/ComparatorForEmployee.java
src/main/java/aqa/core/lesson11/mykhailo_osadtsiv/company/Employee.java
src/main/java/aqa/core/lesson11/mykhailo_osadtsiv/company/EmployeeTerminal.java
src/main/java/aqa/core/lesson11/mykhailo_osadtsiv/company/HumanResourcesDepartment.java
src/main/java/aqa/core/lesson11/mykhailo_osadtsiv/company/MainProgramTerminal.java
src/main/java/aqa/core/lesson11/mykhailo_osadtsiv/company/SalaryReview.java
src/main/java/aqa/core/lesson11/mykhailo_osadtsiv/company/Test.java
src/main/java/aqa/core/lesson11/mykhailo_osadtsiv/company/ToLowSalary.java

All done; can be modified later;

M osadtsiv HW 11

---

src/main/java/aqa/core/lesson11/lpylypenko/Company.java
src/main/java/aqa/core/lesson11/lpylypenko/Employee.java
src/main/java/aqa/core/lesson11/lpylypenko/HomeTasks11.java

Home Task 11 is done by L. Pylypenko.

Home Task 11 is done by L. Pylypenko.

---

src/main/java/aqa/core/lesson11/NazarVdovych_11/Company.java
src/main/java/aqa/core/lesson11/NazarVdovych_11/Employee.java
src/main/java/aqa/core/lesson11/NazarVdovych_11/Main.java

HomeWork11

---

src/main/java/aqa/core/lesson11/lauraShcherbak/Calculation.java
src/main/java/aqa/core/lesson11/lauraShcherbak/Company.java
src/main/java/aqa/core/lesson11/lauraShcherbak/Person.java
src/main/java/aqa/core/lesson11/lauraShcherbak/PersonComparator.java

[Lesson 11] HW 11 added
